package io.getquill.idiom

import io.getquill.NamingStrategy
import io.getquill.ast.Ast

trait IdiomApi[N <: NamingStrategy] {

  def emptySetContainsToken(field: Token): Token = StringToken("FALSE")

  def defaultAutoGeneratedToken(field: Token): Token = StringToken("DEFAULT VALUES")

  def liftingPlaceholder(index: Int): String

  def translate(ast: Ast): (Ast, Statement)

  def prepareForProbing(string: String): String

  implicit def naming: N
}
